apiVersion: v1
kind: Service
metadata:
  name: picnic-vulnapp-service
spec:
  type: LoadBalancer
  selector:
    app: picnic-vulnapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
